### ISSUE TITLE
Anniversary value miscalculated

### ISSUE THREAD

**Issue by jurgenhaas** [amaximus/anniversary#4]
I have events configured like this:

```
platform: anniversary
name: events
multiple: true
anniversaries:
  - event: 'Name'
    date: '1998-10-9'
```

The card properly shows up in the UI. When I open the card and also open attributes, it shows the details. The last line shows `Anniversary: 22` and I guess this is the number of years since the original event. Shouldn't that be 23 in my example?

**Comment by amaximus** [comment]
Thanks for pointing this out.
I just pushed a fix (0.0.4). Please update and get back to me with results.

**Comment by jurgenhaas** [comment]
Just received the update, but the anniversary value is still wrong.

**Comment by amaximus** [comment]
I just set the same date in my test env and it shows 23 for anniversary:

![anniversary_test](https://user-images.githubusercontent.com/2511168/131516041-9b47a071-9da8-452c-876c-47b93eef1305.png)

**Comment by jurgenhaas** [comment]
Oh sorry, the restart of HA after update didn't execute. It's now working correctly, thanks a lot.

**Comment by willvincent** [comment]
0.0.4 is supplying the incorrect calculations now.  Added the anniversary for my in laws (1980) coming up in 5 days. it'll be their 41st anniversary this year, but 0.0.4 calculates it as 42 years.. 0.0.3 displays correctly.

**Comment by amaximus** [comment]
Thanks @willvincent for reporting this.
Fixed in version 0.0.5.

Please update the integration and get back to me with results.

**Comment by willvincent** [comment]
0.0.5 looks good for me 👍

**Comment by jurgenhaas** [comment]
And it still looks good here too
